'use client'

import { X, ShieldCheck, AlertTriangle, Info, Cpu } from 'lucide-react'

interface Props { onClose: () => void }

const sections = [
  {
    icon: <ShieldCheck size={16} className="text-emerald-400" />,
    title: 'No Data Storage or Retention',
    body: 'This tool does not store, log, cache, or persist any sprint data, defect logs, test results, or metrics you submit. All processing is stateless and in-memory. Once your session ends, nothing is retained. Each analysis is fully independent.',
  },
  {
    icon: <Cpu size={16} className="text-[#10B981]" />,
    title: 'Third-Party AI Processing (Anthropic Claude)',
    body: "Your data is transmitted to Anthropic's Claude API over encrypted HTTPS for analysis. Anthropic's own privacy policy governs that transmission. Do not submit sensitive commercial data, PII, or regulated information without reviewing Anthropic's data processing agreements.",
  },
  {
    icon: <AlertTriangle size={16} className="text-amber-400" />,
    title: 'AI Accuracy & Estimation Limitations',
    body: 'Metrics generated by this tool are AI-derived estimates based on the data you provide. They may contain errors, assumptions, or hallucinations — especially when input data is incomplete. Always validate AI-generated metrics against your actual JIRA, TestRail, or other tooling before using them in stakeholder reports.',
  },
  {
    icon: <Info size={16} className="text-[#F59E0B]" />,
    title: 'Not a Substitute for Dedicated Metrics Tooling',
    body: 'This tool provides structured insight from unstructured data — it does not replace dedicated QA metrics platforms (JIRA dashboards, Zephyr, TestRail, etc.). Use it as a quick-analysis lens, not a source of record for your team\'s engineering metrics.',
  },
  {
    icon: <Info size={16} className="text-[#06B6D4]" />,
    title: 'Proof-of-Concept — Self-Developed Tool',
    body: 'This is a personal proof-of-concept independently built and maintained by Atul Sharma, QA Automation Architect. It is provided free of charge for demonstration and educational purposes. No SLA, certification, or formal support is offered.',
  },
  {
    icon: <AlertTriangle size={16} className="text-red-400" />,
    title: 'No Liability',
    body: 'This tool is provided "as is" without warranty. The developer is not liable for any damages arising from use, including incorrect metrics, flawed sprint reports, or decisions made based on AI-generated outputs. Use entirely at your own risk.',
  },
]

export function DisclaimerModal({ onClose }: Props) {
  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center p-4 pt-8 overflow-y-auto">
      <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full max-w-2xl rounded-2xl shadow-2xl animate-fade-in mb-8" style={{ background: 'var(--bg-card)', border: '1px solid var(--border-default)' }}>
        <div className="flex items-center justify-between px-6 py-4 border-b sticky top-0 rounded-t-2xl" style={{ borderColor: 'var(--border-subtle)', background: 'var(--bg-card)' }}>
          <div className="flex items-center gap-2">
            <ShieldCheck size={18} className="text-emerald-400" />
            <h2 className="font-bold text-base" style={{ color: 'var(--text-primary)' }}>Disclaimer & Privacy Notice</h2>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg transition-colors hover:bg-white/[0.07]" style={{ color: 'var(--text-muted)' }}>
            <X size={16} />
          </button>
        </div>

        <div className="px-6 pt-5 pb-2">
          <p className="text-sm leading-relaxed" style={{ color: 'var(--text-muted)' }}>
            Please read before using the{' '}
            <strong style={{ color: 'var(--text-primary)' }}>SDLC Metrics Generator</strong>.
            By using this tool you acknowledge and accept the terms below.
          </p>
        </div>

        <div className="px-6 pb-6 space-y-4 mt-3">
          {sections.map(s => (
            <div key={s.title} className="rounded-xl p-4" style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border-subtle)' }}>
              <div className="flex items-center gap-2 mb-2">
                {s.icon}
                <h3 className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>{s.title}</h3>
              </div>
              <p className="text-xs leading-relaxed" style={{ color: 'var(--text-muted)' }}>{s.body}</p>
            </div>
          ))}

          <div className="rounded-xl p-4 border" style={{ background: 'rgba(16,185,129,0.06)', borderColor: 'rgba(16,185,129,0.2)' }}>
            <p className="text-xs font-medium text-emerald-400 mb-1">In plain English:</p>
            <p className="text-xs leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
              Personal POC project. Your sprint data is never stored. AI can make mistakes — cross-check important numbers. Not a metrics system of record. Developer not liable. Use at your own risk.
            </p>
          </div>
        </div>

        <div className="px-6 py-4 border-t rounded-b-2xl flex items-center justify-between gap-4" style={{ borderColor: 'var(--border-subtle)', background: 'var(--bg-elevated)' }}>
          <p className="text-xs" style={{ color: 'var(--text-dimmer)' }}>Built by Atul Sharma · QA Automation Architect · POC Project</p>
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg text-white text-sm font-medium"
            style={{ background: 'linear-gradient(135deg, #10B981, #F59E0B)' }}
          >
            I Understand
          </button>
        </div>
      </div>
    </div>
  )
}
